#  Telecom Customer Churn Prediction — Data Ingestion & Dataset Understanding
This notebook focuses on loading and understanding the raw Telco Customer Churn dataset before any preprocessing or feature engineering.

## Dataset Information
**Dataset Name:** Telco Customer Churn Dataset

**Target Variable**

`Churn`

- Yes → Customer left the company.
- No → Customer stayed with the company.

In [3]:
#Import Libraries 

import pandas as pd
import numpy as np 

pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",100)

import warnings
warnings.filterwarnings("ignore")

##  Load Raw Dataset

In [6]:
DATA_PATH="../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv"
df=pd.read_csv(DATA_PATH)

In [7]:
#first five previews 
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

##  Dataset Dimensions

In [9]:
rows,columns=df.shape

print(f"Number of rows:{rows}")
print(f"number of columns: {columns}")

print(f"Total Rows and columns {df.shape}")

Number of rows:7043
number of columns: 21
Total Rows and columns (7043, 21)

##  Feature Names

In [14]:
columns_df=pd.DataFrame ({"Column Number":range(1,len(df.columns)+1),"Column Names":df.columns})
columns_df

    Column Number      Column Names
0               1        customerID
1               2            gender
2               3     SeniorCitizen
3               4           Partner
4               5        Dependents
5               6            tenure
6               7      PhoneService
7               8     MultipleLines
8               9   InternetService
9              10    OnlineSecurity
10             11      OnlineBackup
11             12  DeviceProtection
12             13       TechSupport
13             14       StreamingTV
14             15   StreamingMovies
15             16          Contract
16             17  PaperlessBilling
17             18     PaymentMethod
18             19    MonthlyCharges
19             20      TotalCharges
20             21             Churn

##  Dataset Information

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [20]:
#checking for blank value in Total Charges column if present replacing them with np.nan

df["TotalCharges"]=df["TotalCharges"].replace(" ",np.nan)

In [21]:
##  converting Total Charges column from OBJECT to float
df["TotalCharges"]=df["TotalCharges"].astype(float)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

## Numerical vs Categorical Features

In [24]:
categorical_columns=df.select_dtypes(include="object").columns.tolist()

numerical_columns=df.select_dtypes( exclude="object").columns.tolist()

print(f"Categorical Features:{len(categorical_columns)}")
print(categorical_columns)

print("\n" + "="*60)

print(f"Numerical Features:{len(categorical_columns)}")
print(numerical_columns)

Categorical Features:17
['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn']

============================================================
Numerical Features:17
['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

##  Missing Value Analysis

In [27]:
missing_df=pd.DataFrame({"Missing Values":df.isnull().sum(),"Missing Percentage":(df.isnull().sum()/len(df)*100).round(2)})

missing_df.sort_values(by="Missing Percentage",ascending=False)

                  Missing Values  Missing Percentage
TotalCharges                  11                0.16
customerID                     0                0.00
DeviceProtection               0                0.00
MonthlyCharges                 0                0.00
PaymentMethod                  0                0.00
PaperlessBilling               0                0.00
Contract                       0                0.00
StreamingMovies                0                0.00
StreamingTV                    0                0.00
TechSupport                    0                0.00
OnlineBackup                   0                0.00
gender                         0                0.00
OnlineSecurity                 0                0.00
InternetService                0                0.00
MultipleLines                  0                0.00
PhoneService                   0                0.00
tenure                         0                0.00
Dependents                     0                0.00
Partner                        0                0.00
SeniorCitizen                  0                0.00
Churn                          0                0.00

In [28]:
df=df.dropna(subset=["TotalCharges"])

In [29]:
#After dropping Missing value column
missing_df

                  Missing Values  Missing Percentage
customerID                     0                0.00
gender                         0                0.00
SeniorCitizen                  0                0.00
Partner                        0                0.00
Dependents                     0                0.00
tenure                         0                0.00
PhoneService                   0                0.00
MultipleLines                  0                0.00
InternetService                0                0.00
OnlineSecurity                 0                0.00
OnlineBackup                   0                0.00
DeviceProtection               0                0.00
TechSupport                    0                0.00
StreamingTV                    0                0.00
StreamingMovies                0                0.00
Contract                       0                0.00
PaperlessBilling               0                0.00
PaymentMethod                  0                0.00
MonthlyCharges                 0                0.00
TotalCharges                  11                0.16
Churn                          0                0.00

##  Duplicate Record Analysis

In [32]:
duplicated_record=df.duplicated().sum()

print(f"Duplicated Count : {duplicated_record}")

Duplicated Count : 0

##  Unique Values Analysis

In [33]:
unique_df=pd.DataFrame({"Data Type":df.dtypes,"Unique Values":df.nunique()})

unique_df.sort_values(by="Unique Values",ascending= False)

                 Data Type  Unique Values
customerID          object           7032
TotalCharges       float64           6530
MonthlyCharges     float64           1584
tenure               int64             72
PaymentMethod       object              4
DeviceProtection    object              3
Contract            object              3
StreamingMovies     object              3
StreamingTV         object              3
TechSupport         object              3
OnlineBackup        object              3
OnlineSecurity      object              3
InternetService     object              3
MultipleLines       object              3
gender              object              2
PhoneService        object              2
PaperlessBilling    object              2
Dependents          object              2
Partner             object              2
SeniorCitizen        int64              2
Churn               object              2

##  Dataset Memory Usage

In [34]:
memory_usage=df.memory_usage(deep=True).sum()/(1024**2)
print(f"Memory Usage : {memory_usage:.2f} MB")

Memory Usage : 6.55 MB

##  Target Variable Distribution

In [38]:
target_summary= pd.DataFrame({"Count":df["Churn"].value_counts(),"Percentage":(df["Churn"].value_counts(normalize=True)*100).round(2)})
target_summary

       Count  Percentage
Churn
No      5163       73.42
Yes     1869       26.58

#  Data Quality Report

In [39]:
summary_df=pd.DataFrame({"Data Type":df.dtypes,"Missing Values":df.isnull().sum(),"Missing Percentage":(df.isnull().sum()/len(df)*100).round(2),
                         "Unique Values":df.nunique()})

summary_df

                 Data Type  Missing Values  Missing Percentage  Unique Values
customerID          object               0                 0.0           7032
gender              object               0                 0.0              2
SeniorCitizen        int64               0                 0.0              2
Partner             object               0                 0.0              2
Dependents          object               0                 0.0              2
tenure               int64               0                 0.0             72
PhoneService        object               0                 0.0              2
MultipleLines       object               0                 0.0              3
InternetService     object               0                 0.0              3
OnlineSecurity      object               0                 0.0              3
OnlineBackup        object               0                 0.0              3
DeviceProtection    object               0                 0.0              3
TechSupport         object               0                 0.0              3
StreamingTV         object               0                 0.0              3
StreamingMovies     object               0                 0.0              3
Contract            object               0                 0.0              3
PaperlessBilling    object               0                 0.0              2
PaymentMethod       object               0                 0.0              4
MonthlyCharges     float64               0                 0.0           1584
TotalCharges       float64               0                 0.0           6530
Churn               object               0                 0.0              2

In [32]:
%cd "C:\Users\Lenovo\Desktop\github projects\telcos customer churn"

C:\Users\Lenovo\Desktop\github projects\telcos customer churn

In [33]:
import os
print(os.getcwd())

C:\Users\Lenovo\Desktop\github projects\telcos customer churn

## Loading using data_ingestion.py file

In [35]:

from src.data_ingestion import DataIngestion
ingestion=DataIngestion()

df=ingestion.load_data()

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes